document.write('<header>');
document.write('<div id="headerHolder">');
document.write('<img src="images\\Ziggy\\IMG_3933crop.png">');
document.write('<h1>Ziggy</h1>');
document.write('<img src="images\\Ziggy\\IMG_3933crop.png" id="ziggyFlipped">');
document.write('</div>');
document.write('<nav class="navbar">');
document.write('<a role="button" id="homeNav" class="navlink" href="index.html"><i class="fa fa-home fa-lg"></i></a>');
document.write('<a role="button" id="blogNav" class="navlink" href="blog.html">Blog</a>');
document.write('<a role="button" id="familyNav" class="navlink" href="family.html">Family</a>');
document.write('<a role="button" id="imagesNav" class="navlink" href="images.html">Images</a>');
document.write('<a role="button" id="scheduleNav" class="navlink" href="schedule.html">Weekly Schedule</a>');
document.write('<a role="button" id="contactNav" class="navlink" href="contact.html">Contact Me</a>');
document.write('</nav>');
document.write('</header>');