document.write('<script defer src="scripts/animateHeads.js"></script>');
document.write('<script defer src="scripts/navmenuopen.js"></script>');
document.write('<header>');
document.write('<div id="headerHolder">');
document.write('<img alt="Cropped image of Ziggys head" src="images\\Ziggy\\IMG_3933crop.png" id="ziggyPicture">');
document.write('<h1>Ziggy</h1>');
document.write('<img alt="Cropped image of Ziggys head flipped" src="images\\Ziggy\\IMG_3933crop.png" id="ziggyFlipped">');
document.write('</div>');
document.write('<div id="menu-button">');
document.write('<svg viewBox="0 0 100 80" width="30" height="30">');
document.write('<rect fill="lightskyblue" width="100" height="15"></rect>');
document.write('<rect fill="lightskyblue" y="30" width="100" height="15"></rect>');
document.write('<rect fill="lightskyblue" y="60" width="100" height="15"');
document.write('</svg>');
document.write('</div>');
document.write('<nav id="navbar">');
document.write('<a role="button" id="homeNav" class="navlink" href="index.html"><i class="fa fa-home fa-lg"></i></a>');
document.write('<a role="button" id="blogNav" class="navlink" href="blog.html">Blog</a>');
document.write('<a role="button" id="familyNav" class="navlink" href="family.html">Family</a>');
document.write('<a role="button" id="imagesNav" class="navlink" href="images.html">Images</a>');
document.write('<a role="button" id="scheduleNav" class="navlink" href="schedule.html">Daily Schedule</a>');
document.write('<a role="button" id="contactNav" class="navlink" href="contact.html">Contact Me</a>');
document.write('</nav>');
document.write('</header>');